import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'
import Provider from '@/components/Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <div style={{display:'flex',flexDirection:'column',justifyContent:'space-between',minHeight:'95vh'}}>
            <Navbar/>
            {children}
            <Footer/>
          </div>
        </Provider>
      </body>
    </html>
  )
}
